# Generated by Django 3.1.7 on 2021-04-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210410_1630'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='tb_job',
        ),
    ]
