# Generated by Django 3.1.7 on 2021-04-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bachelor_school',
            field=models.CharField(blank=True, max_length=135, verbose_name='本科学校'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='degree',
            field=models.CharField(blank=True, choices=[('本科', '本科'), ('硕士', '硕士'), ('博士', '博士')], max_length=135, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='doctor_school',
            field=models.CharField(blank=True, max_length=135, verbose_name='博士生学校'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='major',
            field=models.CharField(blank=True, max_length=135, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='master_school',
            field=models.CharField(blank=True, max_length=135, verbose_name='研究生学校'),
        ),
    ]
