# Generated by Django 3.1.7 on 2021-04-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20210412_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='paper_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='笔试成绩'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='test_score_of_general_ability',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='综合能力测评成绩'),
        ),
    ]
